17-01-2023

In [1]:
age = 100
print(type(age))

<class 'int'>


In [8]:
age = 20

# all the variables having same data will be pointing to the same memory location
age = age + 1
rak = 20

ind = 20

print(id(ind))
print(id(rak))

print(id(age))

1959014132624
1959014132624
1959014132656


In [10]:
del age
print(age)



NameError: name 'age' is not defined

In [12]:
'''
comments
'''

'\ncomments\n'

## String interpolation/ formatting

In [15]:
age = 60
year = 2023
company = 'futurense'
print("my age is",age)

print(f"my age is {age}")

print(f"my company is {company} and year is {year}")

my age is 60
my age is 60
my company is futurense and year is 2023


In [17]:
username ='rakesh'
message = f'hey user {username}'
print(message)

hey user rakesh


In [19]:
# this will not be updated in message because message is a string 
username = 'sasi'

print(message)

hey user rakesh


In [25]:
print("name {} company{}".format("rakesh","hello"))

name rakesh companyhello


In [27]:
# for exponents the execution starts fromright to left
2**3**2

512

In [28]:
14*2/3+6-2%3-2

11.333333333333334

In [30]:

"""
priority of precedence
1.) **
2.) *, /, %, //
3.) + - 
"""
10*2+6-2%3**2

24

In [15]:

-2 % 3 **2

7

In [48]:
print(2 << 2)
print(2 >> 1)
print(2&1)
print(2 | 1)


8
1
0
3


In [51]:
# membership operator
print(10 in [10,20,30])

's' not in 'school'

True


False

In [21]:
#identity => datatype or object belong to a class

print(type(60) is int)

print(type('hello')is chr)

True
False


In [66]:
# take two numbers from user check if numbers belongs to integers  do arithmetic operation
#else give a  message that values are not integers and take the integers

# inp1 = input("input1: ")
# inp2 = input("input2: ")



    
# print(int(inp1))
    


In [70]:
city ='banglore'
print(city[-1:-6:-1])

print(city[-3::1])

erolg
ore


In [73]:
# when to use for and when to use while
"""
Depends on the situation.
if we know how many times we need to run a loop then moslty we prefer for loop.
Example scenario:
-----------------
print prime numbers below 100  (for loop)
print first 100 prime numbers (while)

"""

for i in range(10):
    print(i)

i = 0
while(i<3):
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
0
1
2


##### Take a input as a password from a user and validate the following conditions.
##### The password should contain alteast 1 cap,  1 small, 1 number [0-6], a special char [@,#, '$',
##### if any condition is not fullfilled then ask for the input from the user upto 3 times
##### after 3rd try print the message "try limit exceeded"
note : don't use any libraries

In [84]:

limit = 3 
small_count = 0
cap_count = 0
special_count = 0
num_count = 0

while(limit > 0):
    password = input("Enter a password: ")
    for character in password:
        if ord(character) >= 65 and ord(character) <= 90 and cap_count == 0:
            cap_count +=1
        elif ord(character) >= 97 and ord(character) <= 122 and small_count == 0:
            small_count +=1
        elif ord(character)>= 48 and ord(character)<=54 and num_count == 0:
            num_count+=1
        elif character in ['@','#','$'] and special_count == 0:
            special_count +=1
        
    if small_count != 0 and cap_count != 0 and special_count != 0 and num_count != 0:
        print("Good password")
        break
    else:
        small_count = 0
        cap_count = 0
        special_count = 0
        num_count = 0
        limit -=1
        if limit == 0:
            print("Try limit exceed")
        
        
            
            

Enter a password: Rakesh123@
Good password


# OPPS

In [23]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    
    def first_name(self):
        return self.name.split()[0]
    
    def age_category(self):
        if self.age < 18:
            return "Child"
        elif self.age >=18 and self.age < 60:
            return "Young person"
        return "Senior citizen"
        
    
p1 = Person("John Doe",37)
print(p1.first_name())

print(p1.age_category())

John
Young person


In [11]:
name = input("Enter the name: ")
while(True):
    try:
        age = int(input("Enter the age: "))
        if age < 0:
            raise Exception()
        else:
            break

    except ValueError:
        print("Age should be int")
    except:
        print("Invalid age")
    
    
        
    
    



Enter the name: khod
Enter the age: -3
Invalid age
Enter the age: skdjfn
Age should be int
Enter the age: 9


In [3]:
while True:
    try:
        year,month,day = map(int, input("Enter dob(yyyy-mm-dd): ").split("-"))
        if year > 1900  and (month>= 1 and month <=12) and (day>0 and day<=31):
            if year % 4 == 0 and (year % 400 == 0 or year % 100 == 0):
                if month == 2 and (day<=29):  
                    print("Valid dob")
            else:
                if month == 2 and day<=28
                    print("valid job")
                    
            break
        else:
            raise Exception()
    except:
        print("Invalid dob")

Enter dob(yyyy-mm-dd): 1980-13-2
Invalid dob
Enter dob(yyyy-mm-dd): 1980-11-31
Valid dob


# Inheritance

In [24]:
class Patient(Person):
    def __init__(self,name,age,ssn):
        super().__init__(name,age)
        self.ssn = ssn
        
    def __str__(self):
        s = "The age of "+str(self.name) +" is " + str(self.age) + ".\n"
        s += "And the Social security number is "+ str(self.ssn)
        return s
   
    def __repr__(self):
        s = f"('{self.name}', {self.age}, {self.ssn})"
        return s
patient1 = Patient("Jhon Doe",40,123443)

print(patient1)
print(patient1.__repr__())

('Jhon Doe', 40, 123443)


In [14]:
patient1.first_name()

'Jhon'

In [49]:
class Person:
    def __init__(self,fname,lname,age):
        self.fname = fname
        self.lname = lname
        self.age = age
        
    def __str__(self):
        s = f"fname: {self.fname}, lname:{self.lname}, age: {self.age}"
        return s

class Student(Person):
    def __init__(self,fname,lname,age,reg_no,maths,science,english):
        super().__init__(fname,lname,age)
        self.reg_no = reg_no
        self.maths = maths
        self.science = science
        self.english = english
    def get_total_marks(self):
        return self.maths + self.science + self.english
    
    def __str__(self):
        s = f"{super().__str__()}, Total marks: {self.get_total_marks()}"
        
        return s
    
    def __repr__(self):
        s = f"({self.fname}, {self.lname}, {self.age}, {self.maths}, {self.science}, {self.english})"
        return s
        
    

class Teacher(Person):
    def __init__(self,fname,lname,age,subjects):
        super().__init__(fname,lname,age)
        self.subjects = subjects
        
    def get_subjects(self):
        return self.subjects
    
    def __str__(self):
        return f"{super().__str__()},subjects: {self.subjects}"
        
    def __repr__(self):
        s = f"({self.fname}, {self.lname}, {self.age}, {self.subjects})"
        return s
        
    
    

t1 = Teacher("Rakesh","reddy",25,['Python','Big-data'])
t2 = Teacher("Virat","Kohli",34,['Airflow','Pyspark'])

print(t1.__str__())
print(t1.get_subjects())

print(t1.__repr__())
        
s1 = Student("Jennifer","Connley",20,'S1234',90,90,95)

print(s1.get_total_marks())

print(s1.__str__())

    

        



fname: Rakesh, lname:reddy, age: 25,subjects: ['Python', 'Big-data']
['Python', 'Big-data']
(Rakesh, reddy, 25, ['Python', 'Big-data'])
275
fname: Jennifer, lname:Connley, age: 20, Total marks: 275


In [51]:
class HOD(Teacher):
    def __init__(self,department,teachers):
        self.deparment = department
        self.teachers = teachers
        
    def get_teacher_details(self):
        for t in self.teachers:
            print(t.__str__())
            
            
h = HOD('Big-data',[t1,t2])

h.get_teacher_details()

fname: Rakesh, lname:reddy, age: 25,subjects: ['Python', 'Big-data']
fname: Virat, lname:Kohli, age: 34,subjects: ['Airflow', 'Pyspark']


# Employees

In [57]:
class Person:
    def __init__(self,name,age,address):
        self.name = name
        self.age = age
        self.address = address
        
    def __str__(self):
        s = f'{self.name}, {self.age}, {self.address}'
        return s
    def __repr__(self):
        s = f'({self.__str__()})'
        return s
    
    
class Employee(Person):
    def __init__(self,name,age,address,salary):
        super().__init__(name,age,address)
        self.salary = salary
    def __str__(self):
        s = f'{super().__str__()}, {self.salary}'
        return s

class SalesEmployee(Employee):
    def __init__(self,name,age,address,salary,bonus):
        super().__init__(name,age,address,salary)
        self.bonus = bonus
    def __str__(self):
        s = f'{super().__str(),{self.bonus}}'
        return s
    
    
class Manager(Person):
    def __init__(self,name,age,address,employees_managed):
        super().__init__(name,age,address)
        self.emp_managed = employees_managed
    def get_employees_details(self):
        for emp in self.emp_managed:
            print(emp.__str__())
            
            
            
e1 = Employee('e1',20,'Banglore',20000)
e2 = Employee('e2',22,'Hyderabad',25000)
e3 = Employee('e3',24,'Mumbai',26000)

m1 = Manager('e_manager',34,'Delhi',[e1,e2,e3])

print(m1.__str__())
m1.get_employees_details()

        

e_manager, 34, Delhi
e1, 20, Banglore, 20000
e2, 22, Hyderabad, 25000
e3, 24, Mumbai, 26000


In [3]:
li = [1,2,3]
li = []

In [21]:
l=['mon','sat','tues','mon','wed','thurs','sat','mon','fri','sun']

d = {}
for val in l:
    d[val] = d.get(val,0)+1
    

k_v = []
k_v.append(list(d.keys()))

k_v.append(list(d.values()))
    
    


In [22]:
k_v

[['mon', 'sat', 'tues', 'wed', 'thurs', 'fri', 'sun'], [3, 2, 1, 1, 1, 1, 1]]

# 24-01-23

In [43]:
x= '''
Exceptional handling uses:
1.) Giving meaningful error messages for the end users.
2.) Keep track of error logs for audit and maintainance
'''

In [64]:
path = 'C:/Users/rakes/OneDrive/Desktop/Assignment_1.txt'
alternate_path = 'C:/Users/rakes/OneDrive/Desktop/Assignment/code.txt'
txt_file = None
try:
    with open(path,'r') as file:
        data = file.read()
        print(data)
except FileNotFoundError as e:
    print("main FileNotFound")
    try:
        txt_file = open(alternate_path,'r')
        print(txt_file)
    except:
        print("Alternate file not found")
except Exception:
    print("Unexpected error")
finally:
    if txt_file is not None:
        txt_file.close()
        print("file closed")
        

main FileNotFound
Alternate file not found


In [68]:
x = 'hello'
if not type(x) is int:
    raise TypeError("X should be int")

TypeError: X should be int

# 28-01-2023

In [16]:
x = '''
1.) difference between py and pyc file.
2.) create a numTobin program and write result into a file using 'wb' mode.
3.) Difference between ASCII and UTF formats?
4.) Why python don't handle the SyntaxError Exception?

'''


In [7]:
fileObj = open('C:/Users/rakes/OneDrive/Desktop/Assignment.txt','r+')

print(fileObj.tell())
data = fileObj.read()

fileObj.write("hey")
print("second time cursor: ",fileObj.tell())
fileObj.close()
print(data)


0
second time cursor:  517
-- 1.
select concat(EmpFname,' ',EmpLname) as fullName from EmployeeInfo
where EmpFname like 'S%' and dob between '02-05-1970' and '31-12-1975';

-- 2.
select  Department,count(EmpID) as deptEmpCount
from EmployeeInfo
group by Department
having count(EmpID) < 2
order by deptEmpCount desc;

-- 3.
select  concat(ei.EmpFname,' ',ei.EmpLname) as full_name,ep.EmpPosition as position from EmployeeInfo ei
inner join EmployeePosition ep 
on ei.EmpID = ep.EmpID
where ep.EmpPosition = 'Manager';heyheyhey


In [14]:
fileObj = open('C:/Users/rakes/OneDrive/Desktop/Assignment.txt','w+')

print(fileObj.tell())
data = fileObj.read()

#seek()  used to change the cursor position
fileObj.seek(2)
fileObj.write("hey")
print("second time cursor: ",fileObj.tell())
fileObj.close()
print(data)


0
second time cursor:  5



In [15]:
# a, a+, ab, (x,a,w => those which are present and not present)


In [33]:
# dir() shows all the attributes and functions present in the file
# class is a template having a set of attributes and methods
# object is any real time implementation of a class / instance of a class
#objects are stored in heap memory and having unique memory addresses.
#constructors are methods to assign memory location to the object

class Futurense:
    def __init__(self,id,name):
        self.id = id
        self.name = name

fObj = Futurense(101,'Rakesh')

fObj.name = 'Rajesh'

fObj.name



'Rajesh'

In [38]:
class hello:
    def __init__(self):
        att = 1
        print("hey")

h = hello()

# att is a local variable and we didn't connected it to the object or class
# why we use self keyword. because there can be many objects . So to access particular object we use self.
h.att


hey


AttributeError: 'hello' object has no attribute 'att'

In [45]:
class Person:
    #here fname and lname are local variables.
    x = 20
    def __init__(self,fname,lname):
        self.fname = fname
        self.lname = lname
    
    
p1 = Person('a','A')
p2 = Person('b','B')
        
print(p1,p2)
print(p1.fname)
print(p2.lname)
print(Person.x)


<__main__.Person object at 0x0000021BBD7E5310> <__main__.Person object at 0x0000021BBD7E5FA0>
a
B
20


In [47]:
# Method Resolution Order mostly happens in Multiple inheritance
# order of execution of classes will be considered for the MRO
'''
class c1:
    abc()
class c2:
    abc()
class c3(c1,c2):
    dab()
c = c3()
c.abc()
c1.abc() will be accessed because it considers classes in order of passing
'''
class Father:
    sal = 25000
    
class Child(Father):
    newSal = 1000
    
c1 = Child()
print(c1.newSal)

1000


# 30-01-2023

In [4]:
class c1:
    def func(self):
        print("c1")
class c2(c1):
    def func(self):
        super().func()
class c3(c2):
    def func(self):
        super().func()
    
c3Obj = c3()


c3.func()

TypeError: func() missing 1 required positional argument: 'self'

In [5]:
## Polymorphism
x ='''
1.) What are dender methods? Uses?
2.)
'''

In [12]:
class Student:
    def studentInfo(self,x):
        print("This is a student class")
class StudentHobbies(Student):
    def studentInfo(self,x):
        super().studentInfo(x)
        print("This is a hobbie class")
        
sh1 = StudentHobbies()

sh1.studentInfo(10)

s = Student()
s.studentInfo(10)

This is a student class
This is a hobbie class
This is a student class


In [29]:
class Futurense:
    def __init__(self,num1,num2):
        self.num1 = num1
        self.num2 = num2
        
    #acts as a representation of the object
    def __str__(self):
        return f"hey num1: {self.num1}, num2: {self.num2}"
    
    def __add__(obj2,self):
        print(self.num1)
        num1 = self.num1 + self.num2
        num2 = obj2.num1 + obj2.num2
        return Futurense(num1,num2)
        
f1 = Futurense(20,10)
print(f1)

f2 = Futurense(30,20)

print(f1+f2)


hey num1: 20, num2: 10
30
hey num1: 50, num2: 30


In [39]:
class Greater:
    def __init__(self,num1,num2):
        self.num1 = num1
        self.num2 = num2
    def __str__(self):
        return f"Data is {self.num1}, {self.num2}"
    def __add__(self,obj1):
        sq1 = self.num1 ** 2 + obj1.num2 **2 # 100 + 49
        sq2 = self.num2 ** 2 + obj1.num2 **2 # 25 + 400
        
        return not (sq1 > sq2)
    
g1 = Greater(10,20) # 100 + 400
g2 = Greater(5,7) # 25 + 49
 
print(g1 + g2)



True


In [44]:
# where the program executions starts
# variable which consists workflow where the program starts
if __name__== "__main__":
    print("hi")

hi


In [45]:
print("name: ",__name__)

name:  __main__


# Encapsulation

In [47]:
# public: accessed any where
# private: accessed only with in the class not in program from same package or other
# protected: they can be accessed with in class and inherited classes from same folder or other
# default( package protected): can be accessed only inside the same package not in other

In [66]:
# and python dont have all the above mentioned keywords. They make use of notations for behave like a access modifiers
# for encapsulation python uses specific concept called notation
# _age representation for protected , __salary represented for private
# the process of python changing the private variable to any variable called as name mangling.

In [95]:
class Trainer:
    
    #private variable
    __salary = 100000
    
    #protected variable 
    _age = 20
    
class Learner(Trainer):
    newPackage = 1000
    
    
l = Learner()
#print(l.__salary)
print(l._Trainer__salary)
    

100000


In [69]:
# name space we can't have duplicates

In [70]:
# Abstraction

In [71]:
# pass will gives us a null pointer reference in the background

In [94]:
# abstract class is a type of class which contains some type of implementation
#such that it should be implemented in the child classes

from abc import ABC, abstractmethod
class Department(ABC):
    salary = 1000
    
    @abstractmethod
    def departmentInfo(self):
        pass
    @abstractmethod
    def test(self):
        print("tested")
    
class DataEngineering(Department):
    salary = 1500
    
    def departmentInfo(self):
        print("hi user")
        
    def test(self):
        print("hi DE user")
        
class hr(DataEngineering):
    def departmentInfo(self):
        print("hr deptinfo")
    
    def testHr(self):
        print("testHr")
        
    def test(self):
        print("hi hr user")
        
        
# d = Department()
md1 = DataEngineering()

h1 = hr()

h1.testHr()
h1.test()






testHr
hi hr user


In [96]:
# class method decorators and static method decorators

In [98]:
import numpy as np

arr_3d = np.array([[[1,2],[3,4]],[[4,5],[6,7]]
    
])

In [99]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [102]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [107]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [108]:
arr1 = np.array([[1,2,3],[3,4,5]])

arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [119]:
arr1.shape = (3,2)
arr1.max(axis=0)

array([4, 5])

In [52]:
import pandas as pd

names = [1,2,3,4]
ids = ['e','r','f','g']

In [53]:
df = pd.DataFrame({'Pname':names,'Pid':ids}, index = ['A','B','C','D'])

In [54]:
df

Pname Pid
A      1   e
B      2   r
C      3   f
D      4   g

In [55]:
df.isna()


Pname    Pid
A  False  False
B  False  False
C  False  False
D  False  False

In [56]:
df.drop_duplicates()

Pname Pid
A      1   e
B      2   r
C      3   f
D      4   g

In [59]:
#df['age'] = [1,2,3,4]
age_df = pd.DataFrame({'age':[1,2,3,4]})
pd.concat((df,age_df))

Pname  Pid  age
A    1.0    e  NaN
B    2.0    r  NaN
C    3.0    f  NaN
D    4.0    g  NaN
0    NaN  NaN  1.0
1    NaN  NaN  2.0
2    NaN  NaN  3.0
3    NaN  NaN  4.0

In [60]:
df.duplicated()

A    False
B    False
C    False
D    False
dtype: bool

In [82]:
string = 'Abc'
new_string = ""
for char in string:
    ascii_code = 122 - abs(65 - ord(char))
    if char.isupper():
        new_string +=chr(ascii_code).upper()
    else:
        new_string+= chr(ascii_code).lower()
        
    

new_string

'Zyx'

In [63]:
ord('a')

97

[65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90]

In [67]:
122- abs(65 - ord('C'))

120

In [6]:
li = [1,2,3,0,1,2,3]

def findEquilibrium(li):
    for i in range(len(li)):
        left_sum = sum(li[:i])
        right_sum = sum(li[i+1:])
        if left_sum == right_sum:
            return i
    return -1


findEquilibrium(li)
    

3

In [8]:
s = {1,}
type(s)

set

In [16]:
10*2+6-2%3**2

24

In [20]:
-6 %9

3

In [26]:
li = iter([1,2,3])

In [29]:
print(next(li))

3
